import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import Navbar from '../components/Navbar'
import PostPreviewCard from '../components/PostPreviewCard'
import { generateCampaignFromSavedUrl, getSavedCampaignPreview } from '../api/client'
import { useToast } from '../context/ToastContext'

function formatSavedAt(value) {
  if (!value) return ''
  try {
    return new Date(value).toLocaleString('pt-BR')
  } catch {
    return String(value)
  }
}

function getPlatformLabel(platform) {
  if ((platform || '').toLowerCase() === 'twitter') return 'X'
  return platform || '-'
}

function getPreviewPlatforms(preview) {
  const values = (preview?.posts || []).map((post) => post.platform).filter(Boolean)
  return [...new Set(values.map((item) => String(item).toLowerCase()))]
}

function isMissingSavedPreviewError(message) {
  const normalized = String(message || '').toLowerCase()
  return normalized.includes('nenhum post salvo') || normalized.includes('nao encontrado')
}

export default function CampaignPreviewPage() {
  const { id } = useParams()
  const { addToast } = useToast()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [preview, setPreview] = useState(null)
  const previewPlatforms = useMemo(() => getPreviewPlatforms(preview), [preview])

  const runGeneration = async ({ autoGenerated = false } = {}) => {
    setLoading(true)
    setError('')
    try {
      const data = await generateCampaignFromSavedUrl(id)
      setPreview(data)
      addToast(autoGenerated ? 'Nao havia posts salvos. Geramos e salvamos agora.' : 'Posts gerados e salvos com base na URL da campanha.')
      return data
    } catch (e) {
      const msg = e.message || 'Erro ao gerar posts da campanha'
      setError(msg)
      addToast(msg, 'error')
      return null
    } finally {
      setLoading(false)
    }
  }

  const loadSavedPreview = async () => {
    setLoading(true)
    setError('')
    try {
      const data = await getSavedCampaignPreview(id)
      setPreview(data)
    } catch (e) {
      const msg = e.message || 'Nenhum post salvo para esta campanha.'
      if (isMissingSavedPreviewError(msg)) {
        const generated = await runGeneration({ autoGenerated: true })
        if (generated) return
      }
      setPreview(null)
      setError(msg)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadSavedPreview()
  }, [id])

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <Navbar />
      <main className="max-w-7xl mx-auto p-6">
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Posts salvos da campanha</h1>
            <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">A tela carrega a ultima geracao salva. Se ainda nao existir um conjunto salvo, a pagina gera e salva automaticamente na primeira abertura.</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => runGeneration()}
              disabled={loading}
              className="bg-primary-500 text-white px-4 py-2 rounded-lg hover:bg-primary-600 disabled:opacity-50"
            >
              {loading ? 'Processando...' : 'Gerar e salvar novamente'}
            </button>
            <Link
              to={`/campaign/${id}`}
              className="border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-200 px-4 py-2 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800"
            >
              Voltar
            </Link>
          </div>
        </div>

        {loading ? (
          <p className="text-gray-500 dark:text-gray-400">Carregando posts salvos...</p>
        ) : error && !preview ? (
          <div className="rounded-lg border border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-950/30 p-4 text-sm text-amber-900 dark:text-amber-100 space-y-3">
            <p>{error}</p>
            <p>Se a campanha tiver URL valida e credenciais configuradas, use o botao acima para tentar uma nova geracao.</p>
          </div>
        ) : !preview ? (
          <p className="text-gray-500 dark:text-gray-400">Nenhum resultado de geracao.</p>
        ) : (
          <>
            <div className="mb-4 rounded-lg border border-gray-200 bg-white p-4 text-sm text-gray-600 shadow-sm dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300">
              <div className="flex flex-wrap gap-4">
                <p><strong>URL base:</strong> {preview.url || '-'}</p>
                {preview.saved_at && <p><strong>Ultimo salvamento:</strong> {formatSavedAt(preview.saved_at)}</p>}
                {preview.saved_content_id && <p><strong>ID salvo:</strong> #{preview.saved_content_id}</p>}
                <p><strong>Total de posts:</strong> {preview.posts?.length || 0}</p>
              </div>
              <div className="mt-3 flex flex-wrap items-center gap-2">
                <strong className="text-gray-700 dark:text-gray-200">Redes:</strong>
                {previewPlatforms.length ? previewPlatforms.map((platform) => (
                  <span key={platform} className="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-700 dark:bg-gray-700 dark:text-gray-200">
                    {getPlatformLabel(platform)}
                  </span>
                )) : <span>-</span>}
              </div>
            </div>
            {preview.error && (
              <div className="rounded-lg border border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-950/30 p-3 text-sm text-amber-900 dark:text-amber-100 mb-4">
                <strong>Erro:</strong> {preview.error}
              </div>
            )}
            {!preview.error && (!preview.posts || preview.posts.length === 0) && (
              <p className="text-sm text-gray-600 dark:text-gray-300 mb-4">
                Nenhum post retornado. Gere novamente apenas se quiser atualizar o conjunto salvo.
              </p>
            )}
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
              {preview.posts?.map((post, i) => (
                <PostPreviewCard key={`${post.platform}-${i}-${post.source_page_url || ''}`} post={post} />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  )
}
